name: WorldChatPrefix
main: io.github.pirgosth.worldchatprefix.WorldChatPrefix
version: 1.0
api-version: 1.15
softdepend: [Multiverse-Core]
author: Pirgosth
commands:
  wcp:
    description: WorldChatPrefix config command
    usage: /<command> [reload]